Repository telvarost/AnnoyanceFix-StationAPI, pull requests merged in 2023-09, with the labels that each got.

#37 Generate better changelogs
  .github/release.yaml
Labels: documentation

#39 Make wooden slabs breakable by hand
  src/main/java/com/github/telvarost/annoyancefix/ModData.java
  src/main/java/com/github/telvarost/annoyancefix/mixin/ItemBaseMixin.java
  src/main/resources/annoyancefix.mixins.json
Labels: bug

#36 Release on modrinth
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: enhancement

#41 Update version number
  gradle.properties
Labels: documentation
